version: '3'
services:
  #  mariadb:
  #    container_name: mariadb
  #    build:
  #      context: .
  #      dockerfile: docker/database/Dockerfile
  #      args:
  #        DATABASE_IMAGE: mariadb
  #        DATABASE_TARGET: mysql
  #    ports:
  #      - "8201:3306"
  #    environment:
  #      MARIADB_RANDOM_ROOT_PASSWORD: yes
  #      MARIADB_DATABASE: inducks
  #    volumes:
  #      - "./db/mariadb:/var/lib/mysql"

  postgres_db:
    container_name: postgres_db
    build:
      context: .
      dockerfile: docker/database/Dockerfile
      args:
        DATABASE_IMAGE: postgres:alpine
        DATABASE_TARGET: postgrest
    ports:
      - "8202:5432"
    environment:
      POSTGRES_DB: inducks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      AUTH_USER: auth
      AUTH_PASSWORD: password
    volumes:
      - "./db/postgres:/var/lib/postgresql/data"

  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    ports:
      - "8203:3000"
    environment:
      PGRST_DB_URI: postgres://auth:password@172.17.0.1:8202/inducks
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:8203
      PGRST_DB_SCHEMAS: inducks
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - postgres_db

  #  swagger:
  #    container_name: swagger
  #    image: spryker/swagger-ui:v3.24.3
  #    ports:
  #      - "8204:8080"
  #    expose:
  #      - "8080"
  #    environment:
  #      API_URL: http://localhost:8201/

  image_proxy:
    container_name: image_proxy
    build: https://github.com/willnorris/imageproxy.git
    ports:
      - "8205:8080"
    volumes:
      - "./image-proxy-cache:/cache"
    environment:
      PUID: 1000
      PGID: 1000
#      IMAGEPROXY_BASEURL: https://inducks.org/hr.php?image=
      IMAGEPROXY_SCALEUP: true
#      IMAGEPROXY_ALLOWHOSTS: "inducks.org,*.dijk.cc"
#      IMAGEPROXY_CACHE: memory:100:24h /cache
      IMAGEPROXY_CACHE: redis://redis:6379
      IMAGEPROXY_VERBOSE: true
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    ports:
      - "6397:6397"
    volumes:
      - ./db/redis:/data
      - ./redis.conf:/usr/local/etc/redis

