version: '3'
services:
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    ports:
      - "8201:3000"
    environment:
      PGRST_DB_URI: postgres://auth:password@db:5432/inducks
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:8081
      PGRST_DB_SCHEMAS: inducks
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - postgres-db
  postgres-db:
    container_name: postgres-db
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - "8202:5432"
    environment:
      POSTGRES_DB: inducks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_AUTH_USER: auth
      POSTGRES_AUTH_PASSWORD: password
    volumes:
      - "./inducks-db-data:/var/lib/postgresql/data"

  swagger:
    container_name: swagger
    image: spryker/swagger-ui:v3.24.3
    ports:
      - "8203:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/

  image-proxy:
    build: https://github.com/willnorris/imageproxy.git
    ports:
      - "8204:8080"

